#!/bin/bash
#
#
for NP in 1
do
 mkdir -p ${NP}p
 rm -rf PROSCAN-G3-LA1-130-${NP}p.in
 ln -s PROSCAN-G3-LA1-130.in PROSCAN-G3-LA1-130-${NP}p.in
 mpirun -np ${NP} $OPAL_EXE_PATH/opal PROSCAN-G3-LA1-130-${NP}p.in | tee PROSCAN-G3-LA1-130-${NP}p.out
 mv *.h5 *.out *.stat *.lbal ${NP}p
 rm -rf data
done