#!/bin/bash

ulimit -m 1800000 -v 1800000
export FIELDMAPS=`pwd`/fieldmaps
export TEMPLATES=`pwd`
export SIMTMPDIR=`pwd`/tmp_sim

# cleanup
if stat -t *_results.dat* >/dev/null 2>&1
then
    rm *_results.dat*
fi

if stat -t PISA_* >/dev/null 2>&1
then
    rm PISA_*
fi

if stat -t *.trace.* >/dev/null 2>&1
then
    rm *.trace.*
fi

if test -d "tmp_sim"; then
    rm -rf tmp_sim
fi
mkdir tmp_sim

mpirun -np 6 ${OPT_BUILD_DIR}/Drivers/pisa-opal/pisa-opal.exe \
    --inputfile=FiPha3Opt1.tmpl --outfile=results.dat --outdir=./ \
    --maxGenerations=10 --initialPopulation=10 \
    --num-masters=2 --num-coworkers=1 --sol-synch=5 \
    --selector=${OPT_BUILD_DIR}/extlib/nsga2/nsga2

