#!/bin/bash

ulimit -m 1800000 -v 1800000
export FIELDMAPS=`pwd`/fieldmaps
export TEMPLATES=`pwd`
export SIMTMPDIR=`pwd`/tmp_sim

# cleanup
if stat -t *_results.dat* >/dev/null 2>&1
then
    rm *_results.dat*
fi

if stat -t PISA_* >/dev/null 2>&1
then
    rm PISA_*
fi

if stat -t *.trace.* >/dev/null 2>&1
then
    rm *.trace.*
fi

if test -d "tmp_sim"; then
    rm -rf tmp_sim
fi
mkdir tmp_sim

mpirun -np 3 ${OPT_BUILD_DIR}/Drivers/homotopy-opal/homotopy-opal.exe \
    --inputfile=FiPha3Opt1.tmpl --outfile=results.dat --outdir=./ \
    --iterations=10 --num-points=100 --num-objectives=3 --num-design-vars=13 \
    --num-masters=1 --num-coworkers=1 --sol-synch=1


