#!/bin/bash

# cleanup
if stat -t *_results.dat* >/dev/null 2>&1
then
    rm *_results.dat*
fi

if stat -t PISA_* >/dev/null 2>&1
then
    rm PISA_*
fi

if stat -t *.trace.* >/dev/null 2>&1
then
    rm *.trace.*
fi

folder=`date +'%d-%m-%Y-%H-%M'`

mpirun -np 6 ${OPT_BUILD_DIR}/Drivers/pisa-standalone/pisa-standalone.exe \
    --inputfile=Problem.in --outfile=results.dat --outdir=./$folder \
    --maxGenerations=10000 --initialPopulation=100 \
    --expected-hypervol=0.6575 --epsilon=2e-4 --one-pilot-converge=1 \
    --num-masters=2 --num-coworkers=1 --sol-synch=100 \
    --selector=${OPT_BUILD_DIR}/extlib/nsga2/nsga2

