#############################################################
# Makefile.def is needed by the test programs
# This should also be replaced by a configure script 
#############################################################
#
# Defines that characterize the architecture.
#

USER_INCLUDES        =  
INCLUDES             =   $(USER_INCLUDES) 
USER_DEFINES         =  -DnoPARALLEL_IO 
DEFINES              =  -DIPPL_MPI -DMPICH_SKIP_MPICXX -DIPPL_DEBUG -DIPPL_GCC -DIPPL_DONT_POOL -DIPPL_USE_XDIV_RNG -DIPPL_LINUX $(USER_DEFINES)
USER_CXXINCLUDES     = 
CXXINCLUDES          =  -I$(IPPL_PREFIX)/include $(USER_CXXINCLUDES) $(INCLUDES)
USER_CINCLUDES       = 
CINCLUDES            =   $(USER_CINCLUDES) $(INCLUDES) 
USER_F77INCLUDES     = 
F77INCLUDES          =   $(USER_F77INCLUDES) $(INCLUDES) 
USER_CXXDEFINES      = 
CXXDEFINES           =  -DIPPL_NO_STRINGSTREAM -DPETE_BITWISE_COPY \
			-DIPPL_USE_STANDARD_HEADERS -DIPPL_USE_PARTIAL_SPECIALIZATION -DIPPL_STDSTL -DIPPL_LONGLONG\
			-DWITH_BRICK -DnoCOMP_GNUOLD -DIPPL_STRINGSTREAM\
			-Drestrict=__restrict__ -DNOCTAssert $(USER_CXXDEFINES) $(DEFINES) 
USER_CDEFINES        = 
CDEFINES             =   $(USER_CDEFINES) $(DEFINES) 
USER_F77DEFINES      = 
F77DEFINES           =   $(USER_F77DEFINES) $(DEFINES) 
USER_CXXOPT          = 
CXXOPT               =   -g $(USER_CXXOPT) 
USER_COPT            = 
COPT                 =   -g $(USER_COPT) 
USER_F77OPT          = 
F77OPT               =   $(USER_F77OPT) 

CXXFLAGS             =  -fpermissive -Wno-deprecated -ftemplate-depth-80 -funroll-loops -fstrict-aliasing $(CXXOPT) $(CXXINCLUDES) $(CXXDEFINES) 

USER_CXXFLAGSLIB     = 
USER_CXXFLAGSAPP     = 
USER_LDFLAGS         = 
CXXFLAGSLIB          =  $(CXXFLAGS) $(USER_CXXFLAGSLIB) 
CXXFLAGSAPP          =  $(CXXFLAGS) $(USER_CXXFLAGSAPP) 
CFLAGS               =  -Drestrict=__restrict__ $(COPT) $(CINCLUDES) $(CDEFINES) 
F77FLAGS             =  -w $(F77OPT) $(F77INCLUDES) $(F77DEFINES) 
F77FLAGSLIB          =  $(F77FLAGS) $(USER_F77FLAGSLIB) 
F77FLAGSAPP          =  $(F77FLAGS) $(USER_F77FLAGSAPP) 
AR                   = ar rc 
CXX_APP_COMPILE_LINE = $(CXX) $(CXXFLAGSAPP) -c 
CXX_LIB_COMPILE_LINE = $(CXX) $(CXXFLAGSLIB) -c 
CC_LIB_COMPILE_LINE      = $(CC) $(CXXFLAGSAPP) -c # $(CFLAGS) -c 
F77_COMPILE_LINE     = $(F77) $(F77FLAGS) -c 
F77AR                = ar rc 
LDFLAGS              =  $(CXXFLAGSAPP) $(USER_LDFLAGS) 

############################################################
# The part below is for linking 
# to include the flags and dependencies for the library.
############################################################

LINKER      = $(CXX)
USER_LFLAGS = 
LFLAGS      = -L$(IPPL_ROOT)/lib/ $(USER_LFLAGS) 
USER_LIBS   = 
LIBS        = -lippl -lm -lstdc++ $(USER_LIBS) 

.cpp.o:
	$(CXX) $(CXXFLAGSAPP) -I. -c $<

.F.o:
	$(F77) $(F77FLAGSAPP) -I. -c $<

.cpp:
	$(CXX) $(CXXFLAGSAPP) -I. -c $<
	$(LINKER) $(LDFLAGS) -o $@ $(<:.cpp=.o) $(LFLAGS) $(LIBS)

.o:
	$(LINKER) $(LDFLAGS) -o $@ $< $(LFLAGS) $(LIBS)
