#!/bin/bash
#
# used modules on merlin00: 1) sge/n1ge6            2) defaultenvironment   3) root/root-5.10.00    4) mpi/mpich-1.2.7
# on Linux (Melrin00)
#
# MERLIN PGI
# Currently Loaded Modulefiles:
#  1) sge/n1ge6                  2) defaultenvironment         3) hdf5/hdf5-1.6.5            4) pgi/pgi-7.1_64             5) mpi/mpich2-1.0.6-pgi-7.0
#
#
mkdir ~/ippl_build
cd ~/ippl_build
CXX=mpicxx F77=gfortran cmake -DCMAKE_VERBOSE_MAKEFILE=OFF -DCMAKE_INSTALL_PREFIX=~/extlib/ippl ~/svnwork/ippl

# Depending on your architecture use on of the following flags:
#   -DLINUXGCC=ON   "Use Linux GCC flags"   DEFAULT
#   -DLINUXPGI=ON   "Use Linux PGI flags"


# build with N threads
make -j N

# note libippl.a and Makefile.def is installed in CMAKE_INSTALL_PREFIX/lib and src/headers installed with a symbolic link in CMAKE_INSTALL_PREFIX/include
make install
