#!/bin/bash
# 
# doAllTests
# 
# 
#
#

for arg in FFT parallel simple speed particle sindex
do
 cd $arg
 echo start test in $arg
 make clean
 make CXX=g++3.2 | tee make.out
 rm *.o
 echo done in echo $arg
 cd ..
done
